### PR TITLE
Add compilation CI

### PR DESCRIPTION
**Pull request by echus**
See https://github.com/ACCESS-NRI/MOM5/issues/3

### CODE REVIEW

**Comment by echus** [comment]
@harshula looks like the build is failing atm:

`==> [2023-06-14-02:08:34.336193] Error: ProcessError: ./MOM_compile.csh: No such file or directory`

Any ideas?

**Comment by harshula** [comment]
Hi,  MOM5's source code is not modified by me. MOM5's SPD contains:
```
        with working_dir(join_path(self.stage.source_path, "exp")):
            build = Executable("./MOM_compile.csh")
```

`self.stage.source_path` would have to be incorrect for  `./MOM_compile.csh` not to be found.

Information about `working_dir`: https://spack.readthedocs.io/en/latest/packaging_guide.html#working-dir

Is it possible to get a directory listing at the location where `./MOM_compile.csh` was executed? e.g.
```
==> [2023-06-14-02:08:34.243730] Created stage in /tmp/root/spack-stage/spack-stage-mom5-3-build-ci-4wuq7nrywonbel7opuztsfnmzo32qcfh
```

**Comment by echus** [comment]
> @harshula looks like the build is failing atm:
> 
> `==> [2023-06-14-02:08:34.336193] Error: ProcessError: ./MOM_compile.csh: No such file or directory`
> 
> Any ideas?

Solved in https://github.com/ACCESS-NRI/build-ci/commit/f88b50ce5ab28180f899ce89e6c26e10c88e9922 by installing csh in the base Docker image.

**Comment by echus** [comment]
@harshula looks like we're getting another build failure on Github Actions. Doesn't occur locally. See: https://github.com/ACCESS-NRI/MOM5/actions/runs/5262225975/jobs/9680881999

I think this is the relevant error:

```
  >> 701    /tmp/root/spack-stage/spack-stage-mom5-3-build-ci-4wuq7nrywonbel7op
            uztsfnmzo32qcfh/spack-src/src/mom5/ocean_core/ocean_model.F90(337):
             error #7002: Error in opening the compiled module file.  Check INC
            LUDE paths.   [VERSION_MOD]
     702    use version_mod,                  only: MOM_COMMIT_HASH
     703    ----^
  >> 704    /tmp/root/spack-stage/spack-stage-mom5-3-build-ci-4wuq7nrywonbel7op
            uztsfnmzo32qcfh/spack-src/src/mom5/ocean_core/ocean_model.F90(337):
             error #6580: Name in only-list does not exist or is not accessible
            .   [MOM_COMMIT_HASH]
     705    use version_mod,                  only: MOM_COMMIT_HASH
     706    ----------------------------------------^
  >> 707    /tmp/root/spack-stage/spack-stage-mom5-3-build-ci-4wuq7nrywonbel7op
            uztsfnmzo32qcfh/spack-src/src/mom5/ocean_core/ocean_model.F90(700):
             error #6404: This name does not have a type, and must have an expl
            icit type.   [MOM_COMMIT_HASH]
     708            write(stdoutunit,*) MOM_COMMIT_HASH
     709    ----------------------------^
     710    compilation aborted for /tmp/root/spack-stage/spack-stage-mom5-3-bu
            ild-ci-4wuq7nrywonbel7opuztsfnmzo32qcfh/spack-src/src/mom5/ocean_co
            re/ocean_model.F90 (code 1)
  >> 711    make: *** [Makefile:241: ocean_model.o] Error 1
     712    Make failed to create lib_ocean.a
```

**Comment by harshula** [comment]
Hi, Follow the same process as last time. See if the `version_mod`  file exits. Also remember: https://github.com/ACCESS-NRI/MOM5/issues/3#issuecomment-1480375893 and Issue https://github.com/ACCESS-NRI/MOM5/issues/4.

**Comment by echus** [comment]
Closing this pull request to open a new one as Github is failing to register the latest commit to 3-build-ci.

**Comment by echus** [comment]
See https://github.com/ACCESS-NRI/MOM5/pull/6 for further work.

**Pull request closed without merging**
