### PR TITLE
Use ACCESS-NRI fork of generic tracers with accessom_coupler

### PR DESCRIPTION
**Pull request by dougiesquire**
See https://github.com/mom-ocean/MOM5/issues/388 for context and details. 

**This PR was [originally made to `mom-ocean/MOM5`](https://github.com/mom-ocean/MOM5/pull/391) but it was decided that we would make the changes here first while some details about the build system and testing are still being resolved.** Comments from @aidanheerdegen's review of the original PR have been incorporated here.

Note, this PR includes the [ACCESS-NRI fork of generic_tracers](https://github.com/ACCESS-NRI/GFDL-generic-tracers) as a git submodule.

Note also, this PR removes the need for the `ACCESS-OM-BGC` build type (and hence the `CSIRO_BGC` pp def). The `ACCESS-OM` build type now always builds with the `USE_OCEAN_BGC` pp def and generic tracer WOMBAT can be configured at runtime. I’ve verified that always building with `USE_OCEAN_BGC` doesn’t impact performance when generic tracers are not configured. To do this, I ran two ACCESS-OM2 experiments on the NCI Gadi supercomputer:

- **Exp 1** uses [this](https://github.com/ACCESS-NRI/access-om2-configs/tree/fce24e35bdf35720a15b6b03fa3616d3486f50b4) configuration modified to run for 1 year at a time and to use a MOM5 executable built from [59e0aad](https://github.com/mom-ocean/MOM5/tree/59e0aad14896027d4c11a936b936a0325e77dbcf) (the most recent commit on `main` at the time of opening this PR).
- **Exp 2** uses the same configuration, but the MOM5 executable used includes the changes in this PR.

I ran three years of each. The experiments were run at the same time. The `chksum` outputs in the logs are identical between the experiments and the walltimes reported by PBS for each year are given in the table below.

  | Exp 1 | Exp 2
-- | -- | --
year 1 | 959 s | 908 s
year 2 | 1031 s | 1002 s
year 3 | 1148 s | 1028 s
average | 1046 s | 979 s

Closes #388

### CODE REVIEW

**Comment by dougiesquire** [comment]
Build CI is failing. I haven't looked in any detail, but one thing sprang to mind - does the build CI need me to make this from a branch in this repo (rather than a fork)? @CodeGat

**Comment by dougiesquire** [comment]
Thanks @CodeGat . I'll also need to add `submodules = True` to the SPD. Does the build CI just use the latest version on `main` of `ACCESS-NRI/spack-packages`?

**Comment by CodeGat** [comment]
No, it uses the latest tagged version - in which case you'll need to push a tag after you've merged the PR (`2024.08.08`)

**Comment by dougiesquire** [comment]
Closing this and will reopen an equivalent PR from a branch in this repo

**Pull request closed without merging**
